---
- name: ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: install_open_jdk
      ansible.builtin.apt module:
       name: openjdk-17-jdk
       state: present
       update_cache: yes
    


