---
- name: ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: install_open_jdk
      ansible.builtin.apt:
       name: "{{ java_package }}"
       state: present
       update_cache: yes
    - name: create_group_tomcat
      ansible.builtin.group:
       name: "{{ group_name }}"
       state: present
       
    - name: add_user_tomcat
      ansible.builtin.user:
       name: "{{ user_name }}"
       create_home: true
       home : "{{ home_dir }}"
       shell : /bin/false
       state: present

    - name: download_tomcat
      ansible.builtin.get_url:
       url: "{{ download_url }}"
       dest: "{{ dest_loc }}"
    - name: unzip
      ansible.builtin.unarchive:
       remote_src: true
       src :  "{{ dest_loc }}"
       dest:  "{{ tomcat_path }}"
    - name: Create_symlink
      ansible.builtin.file:
       src: "{{ tomcat_path }}"
       dest: "{{ tomcat_path }}/latest"
       owner: "{{ user_name }}"
       group: "{{ group_name }}"
       state: link
    - name: "change ownership"
      ansible.builtin.file:
       path: "{{ tomcat_path }}/latest"
       recurse: yes
       owner: "{{ user_name }}"
       group: "{{ group_name }}"
       state: directory
    - name: "give execute permissions"
      ansible.builtin.shell:
       cmd: "chmod +x /opt/tomcat/updated/bin/*.sh"
       executable: "/bin/bash"
      


    

        
       



  
  
  



