---
- name: ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install_open_jdk
      ansible.builtin.apt:
       name: openjdk-17-jdk
       state: present
       update_cache: yes
    - name: install_open_jdk
      ansible.builtin.user:
       name: tomcat
       create_home: true
       home : /opt/tomcat
       shell : /bin/false
       state: present
  
  
  



