---
- name: ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: install_open_jdk
      ansible.builtin.apt:
       name: "{{ java_package }}"
       state: present
       update_cache: yes
    - name: create_group_tomcat
      ansible.builtin.group:
       name: "{{ group_name }}"
       state: present
       
    - name: add_user_tomcat
      ansible.builtin.user:
       name: "{{ user_name }}"
       create_home: true
       home : "{{ home_dir }}"
       shell : /bin/false
       state: present

    - name: download_tomcat
      ansible.builtin.get_url:
       url: "{{ download_url }}"
       dest: "{{ dest_loc }}"
    - name: unzip
      ansible.builtin.unarchive:
       remote_src: true
       src :  "{{ dest_loc }}"
       dest:  "{{ home_dir }}"
       owner: "{{ user_name }}"
       group: "{{ group_name }}"
    - name: Create_symlink
      ansible.builtin.file:
       src: "{{ home_dir }}"
       dest: "{{ tomcat_symlink }}"
       owner: "{{ user_name }}"
       group: "{{ group_name }}"
       state: link
    - name: "change ownership"
      ansible.builtin.file:
       path: "{{ home_dir }}"
       recurse: yes
       owner: "{{ user_name }}"
       group: "{{ group_name }}"
    - name: "give execute permissions"
      ansible.builtin.shell:
       cmd: "chmod +x /opt/tomcat/apache-tomcat-10.1.41/bin/*.sh"
       executable: "/bin/bash"
    - name: copy tomcat.service file
      ansible.builtin.copy:
       src: ~/Ansible_Practise/tomcat.service
       dest: /etc/systemd/system/tomcat.service
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
       enabled: true
       state: started
       name: tomcat.service
    - name: copy tomcat-user.xml
      ansible.builtin.copy:
       src: ~/Ansible_Practise/tomcat-users.xml
       dest: "{{ home_dir }}/apache-tomcat-10.1.41/conf/tomcat-users.xml"
    - name: copy tomcat-context.xml
      ansible.builtin.copy:
       src: ~/Ansible_Practise/tomcat-context.xml
       dest: "{{ home_dir }}/apache-tomcat-10.1.41/webapps/manager/META-INF/context.xml"

    

        
       



  
  
  



