---
- name: Install_tomcat
  hosts: ubuntu
  become: yes
  tasks:
    - name: install openjdk-17-jdk
      ansible.builtin.apt:
       name: "{{ java_package }}"
       state: present
       update_cache: yes
    - name: create_group_tomcat
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present       
    - name: create user tomcat
      ansible.builtin.user:
       name: "{{ user_name }}"
       state: present
       home: "{{ home_dir }}"
       group: "{{ group_name }}"
       shell: "{{ default_shell }}"
    - name: download_tomcat
      ansible.builtin.get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v{{ download_Version }}/bin/apache-tomcat-{{ download_Version }}.tar.gz"
        dest: "{{ download_path }}"
        owner: "{{ user_name }}"
    - name: unarchieve
      ansible.builtin.unarchive:
        src: "{{ download_path }}/apache-tomcat-{{ download_Version }}.tar.gz"
        dest: "{{ home_dir }}"
    - name: Create Sym-link
      ansible.builtin.file:
        state: link
        src: "{{ home_dir }}"
        dest: "{{ tomcat_symlink }}"
    - name: change ownership
      ansible.builtin.file:
       state: directory
       recurse: yes 
       path: "{{ home_dir }}"
       owner: "{{ user_name }}"
       group: "{{ group_name }}"
    - name: give execute Permissions
      ansible.builtin.shell:
       cmd: 'chmod +x {{ home_dir }}/apache-tomcat-{{ download_Version }}/bin/*.sh'
       executable: "/bin/bash"
    - name: create service file
      ansible.builtin.copy:
       src: ~/Ansible_Practise/tomcat.service
       dest: /etc/systemd/system/tomcat.service
    - name: restart systemd
      ansible.builtin.systemd:
       name: tomcat.service
       state: started
       enabled: yes

     
     
     
     
    
    

        
       



  
  
  



