---
- name: Install_tomcat
  hosts: ubuntu
  become: yes
  tasks:
    - name: install openjdk-17-jdk
      ansible.builtin.apt:
       name: "{{ java_package }}"
       state: present
       update_cache: yes
    
    

        
       



  
  
  



