---
- name: ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install_open_jdk
      ansible.builtin.apt:
       name: openjdk-17-jdk
       state: present
       update_cache: yes
    - name: create_group_tomcat
      ansible.builtin.group:
       name: tomcat
       state: present
       
    - name: add_user_tomcat
      ansible.builtin.user:
       name: tomcat
       create_home: true
       home : /opt/tomcat
       shell : /bin/false
       state: present

    - name: download_tomcat
      ansible.builtin.get_url:
       url: https://downloads.apache.org/tomcat/tomcat-10/v10.1.40/bin/apache-tomcat-10.1.40.tar.gz
       dest: /tmp/apache-tomcat-10.1.40.tar.gz
       
  
  
  



